; PlatformIO Project Configuration File
; Replace the contents of your generated platformio.ini with this.

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Set the serial monitor baud rate to match our code
monitor_speed = 115200

; (Optional) Un-comment and specify your COM port if auto-detect fails
; upload_port = COM3
; monitor_port = COM3
